web:
  image: leonhart/warikan
  ports:
    - "80:3000"
  links:
    - mysql
    - redis
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: app_development
  expose:
    - "3306"
redis:
  image: redis
  expose:
    - "6379"
