# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7795aecc6d51585f69d1879b2cc1ec633dee510ae7c71641083fec55fb817a05294e10d451c7ccfb2eb691ba0a70c669b127d4bf19b5821a4330005b2e03a2c

test:
  secret_key_base: b5e5c073dcb4507f8778f1a0e84ca81f72bc6bc954b40303ea76156c4be6a82d904b76911979e7fdc5003c09b0adea389de9d302f354c12ddfb3d7b30206a7f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
